shared:
  resource: ../src/Shared/Presentation/Http/
  type: annotation

user:
  resource: ../src/User/Presentation/Http/
  type: annotation

post:
  resource: ../src/Post/Presentation/Http/
  type: annotation